// Generated by: wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts
// Reflects the bindings declared in wrangler.jsonc.
// Re-run whenever wrangler.jsonc bindings change.

/// <reference types="@cloudflare/workers-types" />

interface CloudflareEnv {
  /** D1 database for orders */
  DB: D1Database;
  /** API key secret for the orders polling API (set via: wrangler secret put ORDERS_API_KEY) */
  ORDERS_API_KEY: string;
  /** Self-reference for internal service dispatch (required by @opennextjs/cloudflare) */
  WORKER_SELF_REFERENCE: Fetcher;
  /** Static assets binding */
  ASSETS: Fetcher;
}
